title:              My Itinerary
email:              your-email@example.com
description:        Creating A Digital Business
author:             Amina
baseurl:            "/"
url:                "https://www.myititnerary.com"

# Social Profiles
twitter_username:   amina_delali
github_username:    amina_delali
facebook_username:  Amina Journey
instagram_username: AminasJourney
linkedin_username:  amina-delali

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
